"""add calibration_map to calibration_results

Revision ID: 395d7dd10690
Revises: 55a8481dfca3
Create Date: 2026-09-25 18:14:45.867789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395d7dd10690'
down_revision: Union[str, Sequence[str], None] = '55a8481dfca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_results', sa.Column('calibration_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibration_results', 'calibration_map')
    # ### end Alembic commands ###
