"""initial schema

Revision ID: b5a3c65eb4fa
Revises: 
Create Date: 2026-09-25 16:36:57.620395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a3c65eb4fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_email'), 'audit_logs', ['actor_email'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_competition_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('competition_type', sa.Enum('DOMESTIC_LEAGUE', 'CUP', 'CONTINENTAL', 'INTERNATIONAL', 'QUALIFYING', 'PLAYOFF', 'YOUTH', 'WOMEN', 'UNKNOWN', name='competitiontype'), nullable=False),
    sa.Column('division_level', sa.Integer(), nullable=True),
    sa.Column('competition_format', sa.Enum('SINGLE_ROUND_ROBIN', 'DOUBLE_ROUND_ROBIN', 'SPLIT_LEAGUE', 'PLAYOFFS', 'GROUP_STAGE', 'KNOCKOUT', 'PROMOTION_RELEGATION_PLAYOFF', 'IRREGULAR', 'UNKNOWN', name='competitionformat'), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'VALIDATING', 'ACTIVE', 'LIMITED_DATA', 'PAUSED', 'FINISHED', 'ARCHIVED', 'ERROR', name='competitionstatus'), nullable=False),
    sa.Column('data_quality_status', sa.Enum('EXCELLENT', 'GOOD', 'LIMITED', 'INSUFFICIENT', name='dataqualitystatus'), nullable=False),
    sa.Column('number_of_teams', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'source_record_id', name='uq_competition_source')
    )
    op.create_index(op.f('ix_competitions_canonical_competition_id'), 'competitions', ['canonical_competition_id'], unique=True)
    op.create_table('provider_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_records_provider_name'), 'provider_records', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_records_source_record_id'), 'provider_records', ['source_record_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_team_id', sa.String(length=64), nullable=False),
    sa.Column('current_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('is_reserve_team', sa.Boolean(), nullable=False),
    sa.Column('is_dissolved', sa.Boolean(), nullable=False),
    sa.Column('merged_into_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'source_record_id', name='uq_team_source')
    )
    op.create_index(op.f('ix_teams_canonical_team_id'), 'teams', ['canonical_team_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', 'SYSTEM', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', 'CHAMPION', 'CHALLENGER', 'RETIRED', name='modelstatus'), nullable=False),
    sa.Column('disabled_reason', sa.String(length=500), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('is_reproducible', sa.Boolean(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_version')
    )
    op.create_index(op.f('ix_model_versions_competition_id'), 'model_versions', ['competition_id'], unique=False)
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('canonical_season_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'FINISHED', name='seasonstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'canonical_season_id', name='uq_season_per_competition')
    )
    op.create_index(op.f('ix_seasons_competition_id'), 'seasons', ['competition_id'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.String(length=32), nullable=True),
    sa.Column('effective_to', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'alias_name', name='uq_team_alias')
    )
    op.create_index(op.f('ix_team_aliases_team_id'), 'team_aliases', ['team_id'], unique=False)
    op.create_table('team_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attack_strength', sa.Float(), nullable=True),
    sa.Column('defence_strength', sa.Float(), nullable=True),
    sa.Column('home_strength', sa.Float(), nullable=True),
    sa.Column('away_strength', sa.Float(), nullable=True),
    sa.Column('opponent_adjusted_strength', sa.Float(), nullable=True),
    sa.Column('recent_strength', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('shrinkage_source', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'competition_id', 'as_of', name='uq_team_strength_snapshot')
    )
    op.create_index(op.f('ix_team_strength_as_of'), 'team_strength', ['as_of'], unique=False)
    op.create_index(op.f('ix_team_strength_competition_id'), 'team_strength', ['competition_id'], unique=False)
    op.create_index(op.f('ix_team_strength_team_id'), 'team_strength', ['team_id'], unique=False)
    op.create_table('calibration_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('forecast_type', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('ranked_probability_score', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('reliability_curve', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_results_competition_id'), 'calibration_results', ['competition_id'], unique=False)
    op.create_index(op.f('ix_calibration_results_model_version_id'), 'calibration_results', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_calibration_results_season_id'), 'calibration_results', ['season_id'], unique=False)
    op.create_table('data_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('EXCELLENT', 'GOOD', 'LIMITED', 'INSUFFICIENT', name='dataqualitystatus'), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('source_reliability', sa.Float(), nullable=True),
    sa.Column('team_mapping_quality', sa.Float(), nullable=True),
    sa.Column('fixture_completeness', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_competition_id'), 'data_quality', ['competition_id'], unique=False)
    op.create_index(op.f('ix_data_quality_season_id'), 'data_quality', ['season_id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_fixture_id', sa.String(length=64), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=64), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'POSTPONED', 'CANCELLED', 'ABANDONED', 'RESCHEDULED', 'IN_PLAY', 'COMPLETED', name='fixturestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'source_record_id', name='uq_fixture_source')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_canonical_fixture_id'), 'fixtures', ['canonical_fixture_id'], unique=True)
    op.create_index(op.f('ix_fixtures_competition_id'), 'fixtures', ['competition_id'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_kickoff_utc'), 'fixtures', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_fixtures_season_id'), 'fixtures', ['season_id'], unique=False)
    op.create_table('league_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('avg_home_goals', sa.Float(), nullable=True),
    sa.Column('avg_away_goals', sa.Float(), nullable=True),
    sa.Column('avg_total_goals', sa.Float(), nullable=True),
    sa.Column('home_advantage', sa.Float(), nullable=True),
    sa.Column('draw_frequency', sa.Float(), nullable=True),
    sa.Column('scoring_variance', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('shrinkage_applied', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'season_id', name='uq_league_parameter')
    )
    op.create_index(op.f('ix_league_parameters_competition_id'), 'league_parameters', ['competition_id'], unique=False)
    op.create_index(op.f('ix_league_parameters_season_id'), 'league_parameters', ['season_id'], unique=False)
    op.create_table('model_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_monitoring_competition_id'), 'model_monitoring', ['competition_id'], unique=False)
    op.create_index(op.f('ix_model_monitoring_model_version_id'), 'model_monitoring', ['model_version_id'], unique=False)
    op.create_table('model_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('learned_from_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learned_from_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'competition_id', name='uq_model_weight')
    )
    op.create_index(op.f('ix_model_weights_competition_id'), 'model_weights', ['competition_id'], unique=False)
    op.create_index(op.f('ix_model_weights_model_version_id'), 'model_weights', ['model_version_id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(length=64), nullable=False),
    sa.Column('stat_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'stat_name', 'team_id', name='uq_match_stat')
    )
    op.create_index(op.f('ix_match_statistics_fixture_id'), 'match_statistics', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_match_statistics_team_id'), 'match_statistics', ['team_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=False),
    sa.Column('software_version', sa.String(length=64), nullable=False),
    sa.Column('score_matrix', sa.JSON(), nullable=False),
    sa.Column('expected_goals_home', sa.Float(), nullable=True),
    sa.Column('expected_goals_away', sa.Float(), nullable=True),
    sa.Column('outcome_probabilities', sa.JSON(), nullable=False),
    sa.Column('goal_distribution', sa.JSON(), nullable=True),
    sa.Column('forecast_status', sa.Enum('ACTIVE', 'LIMITED', 'FAILED_VALIDATION', name='forecaststatus'), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('aleatoric_uncertainty', sa.Float(), nullable=True),
    sa.Column('epistemic_uncertainty', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('model_disagreement_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='disagreementlevel'), nullable=True),
    sa.Column('ood_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_fixture_id'), 'predictions', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=True)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('home_goals_first_half', sa.Integer(), nullable=True),
    sa.Column('away_goals_first_half', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_table('xg_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('home_xg_first_half', sa.Float(), nullable=True),
    sa.Column('away_xg_first_half', sa.Float(), nullable=True),
    sa.Column('shot_level_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_table('prediction_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('model_configuration', sa.JSON(), nullable=False),
    sa.Column('snapshot_taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('scenario_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('baseline_prediction_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('scenario_result', sa.JSON(), nullable=False),
    sa.Column('difference', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_predictions_fixture_id'), 'scenario_predictions', ['fixture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_predictions_fixture_id'), table_name='scenario_predictions')
    op.drop_table('scenario_predictions')
    op.drop_table('prediction_snapshots')
    op.drop_table('xg_data')
    op.drop_table('results')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_fixture_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_match_statistics_team_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_fixture_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index(op.f('ix_model_weights_model_version_id'), table_name='model_weights')
    op.drop_index(op.f('ix_model_weights_competition_id'), table_name='model_weights')
    op.drop_table('model_weights')
    op.drop_index(op.f('ix_model_monitoring_model_version_id'), table_name='model_monitoring')
    op.drop_index(op.f('ix_model_monitoring_competition_id'), table_name='model_monitoring')
    op.drop_table('model_monitoring')
    op.drop_index(op.f('ix_league_parameters_season_id'), table_name='league_parameters')
    op.drop_index(op.f('ix_league_parameters_competition_id'), table_name='league_parameters')
    op.drop_table('league_parameters')
    op.drop_index(op.f('ix_fixtures_season_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_kickoff_utc'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_competition_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_canonical_fixture_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_data_quality_season_id'), table_name='data_quality')
    op.drop_index(op.f('ix_data_quality_competition_id'), table_name='data_quality')
    op.drop_table('data_quality')
    op.drop_index(op.f('ix_calibration_results_season_id'), table_name='calibration_results')
    op.drop_index(op.f('ix_calibration_results_model_version_id'), table_name='calibration_results')
    op.drop_index(op.f('ix_calibration_results_competition_id'), table_name='calibration_results')
    op.drop_table('calibration_results')
    op.drop_index(op.f('ix_team_strength_team_id'), table_name='team_strength')
    op.drop_index(op.f('ix_team_strength_competition_id'), table_name='team_strength')
    op.drop_index(op.f('ix_team_strength_as_of'), table_name='team_strength')
    op.drop_table('team_strength')
    op.drop_index(op.f('ix_team_aliases_team_id'), table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index(op.f('ix_seasons_competition_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_competition_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_canonical_team_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_provider_records_source_record_id'), table_name='provider_records')
    op.drop_index(op.f('ix_provider_records_provider_name'), table_name='provider_records')
    op.drop_table('provider_records')
    op.drop_index(op.f('ix_competitions_canonical_competition_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_audit_logs_actor_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
